[[redirects]]
from = "/birthday/*"
to = "/templates/birthday/index.html"
status = 200

[[redirects]]
from = "/anniversary/*"
to = "/templates/anniversary/index.html"
status = 200

# =========================
# BOYFRIEND'S DAY
# =========================

[[redirects]]
from = "/boyfriends-day/*"
to = "/templates/boyfriends-day/index.html"
status = 200